language: scala
scala:
- 2.11.11
- 2.12.8
before_install:
- git fetch --tags
stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  # run ci-release only if previous stages passed
  - stage: release
    script: sbt ci-release

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
